# 默认配置文件

# 服务器配置
server:
  host: 192.168.31.35  # 算力自调配服务器的IP地址
  port: 3000         # Socket服务端口号

# 节点配置
node:
  ip: 192.168.31.133    # 节点IP地址，用于与算力自调配服务器通信

# 日志配置
logging:
  level: info        # 日志级别：error(错误)、warning(警告)、info(通知) 